// automatically generated by the FlatBuffers compiler, do not modify

import * as NS8382949480189395168 from "./types_generated";
/**
 * @constructor
 */
export namespace binary{
export class Point {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Point
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Point {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns number
 */
x():number {
  return this.bb!.readFloat32(this.bb_pos);
};

/**
 * @returns number
 */
y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param number x
 * @param number y
 * @returns flatbuffers.Offset
 */
static createPoint(builder:flatbuffers.Builder, x: number, y: number):flatbuffers.Offset {
  builder.prep(4, 8);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
};

}
}
/**
 * @constructor
 */
export namespace binary{
export class Matrix {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Matrix
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Matrix {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @returns number
 */
a():number {
  return this.bb!.readFloat32(this.bb_pos);
};

/**
 * @returns number
 */
b():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
};

/**
 * @returns number
 */
c():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
};

/**
 * @returns number
 */
d():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
};

/**
 * @returns number
 */
e():number {
  return this.bb!.readFloat32(this.bb_pos + 16);
};

/**
 * @returns number
 */
f():number {
  return this.bb!.readFloat32(this.bb_pos + 20);
};

/**
 * @param flatbuffers.Builder builder
 * @param number a
 * @param number b
 * @param number c
 * @param number d
 * @param number e
 * @param number f
 * @returns flatbuffers.Offset
 */
static createMatrix(builder:flatbuffers.Builder, a: number, b: number, c: number, d: number, e: number, f: number):flatbuffers.Offset {
  builder.prep(4, 24);
  builder.writeFloat32(f);
  builder.writeFloat32(e);
  builder.writeFloat32(d);
  builder.writeFloat32(c);
  builder.writeFloat32(b);
  builder.writeFloat32(a);
  return builder.offset();
};

}
}
/**
 * @constructor
 */
export namespace binary{
export class Database {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Database
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Database {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Database= obj
 * @returns Database
 */
static getRootAsDatabase(bb:flatbuffers.ByteBuffer, obj?:Database):Database {
  return (obj || new Database).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Database= obj
 * @returns Database
 */
static getSizePrefixedRootAsDatabase(bb:flatbuffers.ByteBuffer, obj?:Database):Database {
  return (obj || new Database).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
engine():string|null
engine(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
engine(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns binary.DatabaseType
 */
type():NS8382949480189395168.binary.DatabaseType {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : NS8382949480189395168.binary.DatabaseType.RDMS;
};

/**
 * @param number index
 * @param binary.Table= obj
 * @returns binary.Table
 */
tables(index: number, obj?:binary.Table):binary.Table|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new binary.Table).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
tablesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param binary.Matrix= obj
 * @returns binary.Matrix|null
 */
matrix(obj?:binary.Matrix):binary.Matrix|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new binary.Matrix).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @returns flatbuffers.Long
 */
createdAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
lastUpdateAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Builder builder
 */
static startDatabase(builder:flatbuffers.Builder) {
  builder.startObject(8);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset engineOffset
 */
static addEngine(builder:flatbuffers.Builder, engineOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, engineOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param binary.DatabaseType type
 */
static addType(builder:flatbuffers.Builder, type:NS8382949480189395168.binary.DatabaseType) {
  builder.addFieldInt8(3, type, NS8382949480189395168.binary.DatabaseType.RDMS);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset tablesOffset
 */
static addTables(builder:flatbuffers.Builder, tablesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, tablesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createTablesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startTablesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset matrixOffset
 */
static addMatrix(builder:flatbuffers.Builder, matrixOffset:flatbuffers.Offset) {
  builder.addFieldStruct(5, matrixOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long createdAt
 */
static addCreatedAt(builder:flatbuffers.Builder, createdAt:flatbuffers.Long) {
  builder.addFieldInt64(6, createdAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long lastUpdateAt
 */
static addLastUpdateAt(builder:flatbuffers.Builder, lastUpdateAt:flatbuffers.Long) {
  builder.addFieldInt64(7, lastUpdateAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endDatabase(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // id
  builder.requiredField(offset, 6); // name
  return offset;
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishDatabaseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset offset
 */
static finishSizePrefixedDatabaseBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined);
};

static createDatabase(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, engineOffset:flatbuffers.Offset, type:NS8382949480189395168.binary.DatabaseType, tablesOffset:flatbuffers.Offset, matrixOffset:flatbuffers.Offset, createdAt:flatbuffers.Long, lastUpdateAt:flatbuffers.Long):flatbuffers.Offset {
  Database.startDatabase(builder);
  Database.addId(builder, idOffset);
  Database.addName(builder, nameOffset);
  Database.addEngine(builder, engineOffset);
  Database.addType(builder, type);
  Database.addTables(builder, tablesOffset);
  Database.addMatrix(builder, matrixOffset);
  Database.addCreatedAt(builder, createdAt);
  Database.addLastUpdateAt(builder, lastUpdateAt);
  return Database.endDatabase(builder);
}
}
}
/**
 * @constructor
 */
export namespace binary{
export class Table {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Table
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Table {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Table= obj
 * @returns Table
 */
static getRootAsTable(bb:flatbuffers.ByteBuffer, obj?:Table):Table {
  return (obj || new Table).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Table= obj
 * @returns Table
 */
static getSizePrefixedRootAsTable(bb:flatbuffers.ByteBuffer, obj?:Table):Table {
  return (obj || new Table).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param number index
 * @param binary.Field= obj
 * @returns binary.Field
 */
fields(index: number, obj?:binary.Field):binary.Field|null {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new binary.Field).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
fieldsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
primaries(index: number):string
primaries(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
primaries(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
primariesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param binary.KeyGroup= obj
 * @returns binary.KeyGroup
 */
uniques(index: number, obj?:binary.KeyGroup):binary.KeyGroup|null {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new binary.KeyGroup).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
uniquesLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param binary.KeyGroup= obj
 * @returns binary.KeyGroup
 */
foriegns(index: number, obj?:binary.KeyGroup):binary.KeyGroup|null {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? (obj || new binary.KeyGroup).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
foriegnsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param binary.Point= obj
 * @returns binary.Point|null
 */
position(obj?:binary.Point):binary.Point|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? (obj || new binary.Point).__init(this.bb_pos + offset, this.bb!) : null;
};

/**
 * @returns flatbuffers.Long
 */
createdAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
lastUpdateAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Builder builder
 */
static startTable(builder:flatbuffers.Builder) {
  builder.startObject(9);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset fieldsOffset
 */
static addFields(builder:flatbuffers.Builder, fieldsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, fieldsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createFieldsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startFieldsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset primariesOffset
 */
static addPrimaries(builder:flatbuffers.Builder, primariesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, primariesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createPrimariesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startPrimariesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset uniquesOffset
 */
static addUniques(builder:flatbuffers.Builder, uniquesOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, uniquesOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createUniquesVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startUniquesVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset foriegnsOffset
 */
static addForiegns(builder:flatbuffers.Builder, foriegnsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(5, foriegnsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createForiegnsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startForiegnsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset positionOffset
 */
static addPosition(builder:flatbuffers.Builder, positionOffset:flatbuffers.Offset) {
  builder.addFieldStruct(6, positionOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long createdAt
 */
static addCreatedAt(builder:flatbuffers.Builder, createdAt:flatbuffers.Long) {
  builder.addFieldInt64(7, createdAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long lastUpdateAt
 */
static addLastUpdateAt(builder:flatbuffers.Builder, lastUpdateAt:flatbuffers.Long) {
  builder.addFieldInt64(8, lastUpdateAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endTable(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // id
  builder.requiredField(offset, 6); // name
  return offset;
};

static createTable(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, fieldsOffset:flatbuffers.Offset, primariesOffset:flatbuffers.Offset, uniquesOffset:flatbuffers.Offset, foriegnsOffset:flatbuffers.Offset, positionOffset:flatbuffers.Offset, createdAt:flatbuffers.Long, lastUpdateAt:flatbuffers.Long):flatbuffers.Offset {
  Table.startTable(builder);
  Table.addId(builder, idOffset);
  Table.addName(builder, nameOffset);
  Table.addFields(builder, fieldsOffset);
  Table.addPrimaries(builder, primariesOffset);
  Table.addUniques(builder, uniquesOffset);
  Table.addForiegns(builder, foriegnsOffset);
  Table.addPosition(builder, positionOffset);
  Table.addCreatedAt(builder, createdAt);
  Table.addLastUpdateAt(builder, lastUpdateAt);
  return Table.endTable(builder);
}
}
}
/**
 * @constructor
 */
export namespace binary{
export class KeyGroup {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns KeyGroup
 */
__init(i:number, bb:flatbuffers.ByteBuffer):KeyGroup {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param KeyGroup= obj
 * @returns KeyGroup
 */
static getRootAsKeyGroup(bb:flatbuffers.ByteBuffer, obj?:KeyGroup):KeyGroup {
  return (obj || new KeyGroup).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param KeyGroup= obj
 * @returns KeyGroup
 */
static getSizePrefixedRootAsKeyGroup(bb:flatbuffers.ByteBuffer, obj?:KeyGroup):KeyGroup {
  return (obj || new KeyGroup).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
ids(index: number):string
ids(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
ids(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
idsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
key():string|null
key(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
key(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Builder builder
 */
static startKeyGroup(builder:flatbuffers.Builder) {
  builder.startObject(2);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idsOffset
 */
static addIds(builder:flatbuffers.Builder, idsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createIdsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startIdsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset keyOffset
 */
static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endKeyGroup(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createKeyGroup(builder:flatbuffers.Builder, idsOffset:flatbuffers.Offset, keyOffset:flatbuffers.Offset):flatbuffers.Offset {
  KeyGroup.startKeyGroup(builder);
  KeyGroup.addIds(builder, idsOffset);
  KeyGroup.addKey(builder, keyOffset);
  return KeyGroup.endKeyGroup(builder);
}
}
}
/**
 * @constructor
 */
export namespace binary{
export class Field {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns Field
 */
__init(i:number, bb:flatbuffers.ByteBuffer):Field {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Field= obj
 * @returns Field
 */
static getRootAsField(bb:flatbuffers.ByteBuffer, obj?:Field):Field {
  return (obj || new Field).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param Field= obj
 * @returns Field
 */
static getSizePrefixedRootAsField(bb:flatbuffers.ByteBuffer, obj?:Field):Field {
  return (obj || new Field).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
id():string|null
id(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
id(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns binary.DataType
 */
type():NS8382949480189395168.binary.DataType {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : NS8382949480189395168.binary.DataType.Unknown;
};

/**
 * @returns number
 */
size():number {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
digit():number {
  var offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns number
 */
fpoint():number {
  var offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @param number index
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array
 */
items(index: number):string
items(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
items(index: number,optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
};

/**
 * @returns number
 */
itemsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @returns binary.FieldKind
 */
kind():NS8382949480189395168.binary.FieldKind {
  var offset = this.bb!.__offset(this.bb_pos, 18);
  return offset ? /**  */ (this.bb!.readUint8(this.bb_pos + offset)) : NS8382949480189395168.binary.FieldKind.Normal;
};

/**
 * @returns boolean
 */
key():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 20);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param number index
 * @param binary.UtilizedField= obj
 * @returns binary.UtilizedField
 */
utilizeds(index: number, obj?:binary.UtilizedField):binary.UtilizedField|null {
  var offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? (obj || new binary.UtilizedField).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
};

/**
 * @returns number
 */
utilizedsLength():number {
  var offset = this.bb!.__offset(this.bb_pos, 22);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
};

/**
 * @param binary.ReferenceField= obj
 * @returns binary.ReferenceField|null
 */
reference(obj?:binary.ReferenceField):binary.ReferenceField|null {
  var offset = this.bb!.__offset(this.bb_pos, 24);
  return offset ? (obj || new binary.ReferenceField).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
};

/**
 * @returns number
 */
order():number {
  var offset = this.bb!.__offset(this.bb_pos, 26);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
};

/**
 * @returns flatbuffers.Long
 */
createdAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 28);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @returns flatbuffers.Long
 */
lastUpdateAt():flatbuffers.Long {
  var offset = this.bb!.__offset(this.bb_pos, 30);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : this.bb!.createLong(0, 0);
};

/**
 * @param flatbuffers.Builder builder
 */
static startField(builder:flatbuffers.Builder) {
  builder.startObject(14);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset idOffset
 */
static addId(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, idOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset nameOffset
 */
static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, nameOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param binary.DataType type
 */
static addType(builder:flatbuffers.Builder, type:NS8382949480189395168.binary.DataType) {
  builder.addFieldInt8(2, type, NS8382949480189395168.binary.DataType.Unknown);
};

/**
 * @param flatbuffers.Builder builder
 * @param number size
 */
static addSize(builder:flatbuffers.Builder, size:number) {
  builder.addFieldInt16(3, size, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number digit
 */
static addDigit(builder:flatbuffers.Builder, digit:number) {
  builder.addFieldInt8(4, digit, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number fpoint
 */
static addFpoint(builder:flatbuffers.Builder, fpoint:number) {
  builder.addFieldInt8(5, fpoint, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset itemsOffset
 */
static addItems(builder:flatbuffers.Builder, itemsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(6, itemsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createItemsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startItemsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param binary.FieldKind kind
 */
static addKind(builder:flatbuffers.Builder, kind:NS8382949480189395168.binary.FieldKind) {
  builder.addFieldInt8(7, kind, NS8382949480189395168.binary.FieldKind.Normal);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean key
 */
static addKey(builder:flatbuffers.Builder, key:boolean) {
  builder.addFieldInt8(8, +key, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset utilizedsOffset
 */
static addUtilizeds(builder:flatbuffers.Builder, utilizedsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(9, utilizedsOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param Array.<flatbuffers.Offset> data
 * @returns flatbuffers.Offset
 */
static createUtilizedsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (var i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]);
  }
  return builder.endVector();
};

/**
 * @param flatbuffers.Builder builder
 * @param number numElems
 */
static startUtilizedsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset referenceOffset
 */
static addReference(builder:flatbuffers.Builder, referenceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(10, referenceOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param number order
 */
static addOrder(builder:flatbuffers.Builder, order:number) {
  builder.addFieldInt8(11, order, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long createdAt
 */
static addCreatedAt(builder:flatbuffers.Builder, createdAt:flatbuffers.Long) {
  builder.addFieldInt64(12, createdAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Long lastUpdateAt
 */
static addLastUpdateAt(builder:flatbuffers.Builder, lastUpdateAt:flatbuffers.Long) {
  builder.addFieldInt64(13, lastUpdateAt, builder.createLong(0, 0));
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endField(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  builder.requiredField(offset, 4); // id
  builder.requiredField(offset, 6); // name
  return offset;
};

static createField(builder:flatbuffers.Builder, idOffset:flatbuffers.Offset, nameOffset:flatbuffers.Offset, type:NS8382949480189395168.binary.DataType, size:number, digit:number, fpoint:number, itemsOffset:flatbuffers.Offset, kind:NS8382949480189395168.binary.FieldKind, key:boolean, utilizedsOffset:flatbuffers.Offset, referenceOffset:flatbuffers.Offset, order:number, createdAt:flatbuffers.Long, lastUpdateAt:flatbuffers.Long):flatbuffers.Offset {
  Field.startField(builder);
  Field.addId(builder, idOffset);
  Field.addName(builder, nameOffset);
  Field.addType(builder, type);
  Field.addSize(builder, size);
  Field.addDigit(builder, digit);
  Field.addFpoint(builder, fpoint);
  Field.addItems(builder, itemsOffset);
  Field.addKind(builder, kind);
  Field.addKey(builder, key);
  Field.addUtilizeds(builder, utilizedsOffset);
  Field.addReference(builder, referenceOffset);
  Field.addOrder(builder, order);
  Field.addCreatedAt(builder, createdAt);
  Field.addLastUpdateAt(builder, lastUpdateAt);
  return Field.endField(builder);
}
}
}
/**
 * @constructor
 */
export namespace binary{
export class ReferenceField {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns ReferenceField
 */
__init(i:number, bb:flatbuffers.ByteBuffer):ReferenceField {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ReferenceField= obj
 * @returns ReferenceField
 */
static getRootAsReferenceField(bb:flatbuffers.ByteBuffer, obj?:ReferenceField):ReferenceField {
  return (obj || new ReferenceField).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param ReferenceField= obj
 * @returns ReferenceField
 */
static getSizePrefixedRootAsReferenceField(bb:flatbuffers.ByteBuffer, obj?:ReferenceField):ReferenceField {
  return (obj || new ReferenceField).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
origin():string|null
origin(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
origin(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
source():string|null
source(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
source(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns boolean
 */
weak():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
reference():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Builder builder
 */
static startReferenceField(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset originOffset
 */
static addOrigin(builder:flatbuffers.Builder, originOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, originOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset sourceOffset
 */
static addSource(builder:flatbuffers.Builder, sourceOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, sourceOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean weak
 */
static addWeak(builder:flatbuffers.Builder, weak:boolean) {
  builder.addFieldInt8(2, +weak, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean reference
 */
static addReference(builder:flatbuffers.Builder, reference:boolean) {
  builder.addFieldInt8(3, +reference, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endReferenceField(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createReferenceField(builder:flatbuffers.Builder, originOffset:flatbuffers.Offset, sourceOffset:flatbuffers.Offset, weak:boolean, reference:boolean):flatbuffers.Offset {
  ReferenceField.startReferenceField(builder);
  ReferenceField.addOrigin(builder, originOffset);
  ReferenceField.addSource(builder, sourceOffset);
  ReferenceField.addWeak(builder, weak);
  ReferenceField.addReference(builder, reference);
  return ReferenceField.endReferenceField(builder);
}
}
}
/**
 * @constructor
 */
export namespace binary{
export class UtilizedField {
  bb: flatbuffers.ByteBuffer|null = null;

  bb_pos:number = 0;
/**
 * @param number i
 * @param flatbuffers.ByteBuffer bb
 * @returns UtilizedField
 */
__init(i:number, bb:flatbuffers.ByteBuffer):UtilizedField {
  this.bb_pos = i;
  this.bb = bb;
  return this;
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UtilizedField= obj
 * @returns UtilizedField
 */
static getRootAsUtilizedField(bb:flatbuffers.ByteBuffer, obj?:UtilizedField):UtilizedField {
  return (obj || new UtilizedField).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.ByteBuffer bb
 * @param UtilizedField= obj
 * @returns UtilizedField
 */
static getSizePrefixedRootAsUtilizedField(bb:flatbuffers.ByteBuffer, obj?:UtilizedField):UtilizedField {
  return (obj || new UtilizedField).__init(bb.readInt32(bb.position()) + bb.position(), bb);
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
target():string|null
target(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
target(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @param flatbuffers.Encoding= optionalEncoding
 * @returns string|Uint8Array|null
 */
destination():string|null
destination(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
destination(optionalEncoding?:any):string|Uint8Array|null {
  var offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
};

/**
 * @returns boolean
 */
weak():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @returns boolean
 */
reference():boolean {
  var offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
};

/**
 * @param flatbuffers.Builder builder
 */
static startUtilizedField(builder:flatbuffers.Builder) {
  builder.startObject(4);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset targetOffset
 */
static addTarget(builder:flatbuffers.Builder, targetOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, targetOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param flatbuffers.Offset destinationOffset
 */
static addDestination(builder:flatbuffers.Builder, destinationOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, destinationOffset, 0);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean weak
 */
static addWeak(builder:flatbuffers.Builder, weak:boolean) {
  builder.addFieldInt8(2, +weak, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @param boolean reference
 */
static addReference(builder:flatbuffers.Builder, reference:boolean) {
  builder.addFieldInt8(3, +reference, +false);
};

/**
 * @param flatbuffers.Builder builder
 * @returns flatbuffers.Offset
 */
static endUtilizedField(builder:flatbuffers.Builder):flatbuffers.Offset {
  var offset = builder.endObject();
  return offset;
};

static createUtilizedField(builder:flatbuffers.Builder, targetOffset:flatbuffers.Offset, destinationOffset:flatbuffers.Offset, weak:boolean, reference:boolean):flatbuffers.Offset {
  UtilizedField.startUtilizedField(builder);
  UtilizedField.addTarget(builder, targetOffset);
  UtilizedField.addDestination(builder, destinationOffset);
  UtilizedField.addWeak(builder, weak);
  UtilizedField.addReference(builder, reference);
  return UtilizedField.endUtilizedField(builder);
}
}
}
