// automatically generated by the FlatBuffers compiler, do not modify

/**
 * @enum {number}
 */
export namespace Document{
export enum DataType{
  Unknown= 0,
  Number= 1,
  Bit= 2,
  TinyInt= 3,
  SmallInt= 4,
  Medium= 5,
  Int= 6,
  BigInt= 7,
  Decimal= 8,
  Numeric= 9,
  Float= 10,
  Real= 11,
  Double= 12,
  String= 13,
  Char= 14,
  VarChar= 15,
  Text= 16,
  DateTime= 17,
  Date= 18,
  Time= 19,
  TimeStamp= 20,
  Year= 21,
  Enum= 22,
  Binary= 23,
  VarBinary= 24,
  Image= 25,
  Miscellaneous= 26,
  Clob= 27,
  Blob= 28,
  XML= 29,
  Json= 30,
  Set= 31,
  Bool= 32,
  Boolean= 33,
  UnicodeChar= 34,
  UnicodeVarChar= 35,
  UnicodeText= 36
}};

/**
 * @enum {number}
 */
export namespace Document{
export enum DatabaseType{
  RDMS= 0,
  NOSQL= 1,
  GRAPH= 2
}};

/**
 * @enum {number}
 */
export namespace Document{
export enum FieldKind{
  Normal= 0,
  Primary= 1,
  Unique= 2,
  Foriegn= 3
}};

